# Generated by Django 3.2.9 on 2021-12-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
