# Generated by Django 3.2.9 on 2021-12-08 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_post_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='good',
        ),
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.ManyToManyField(blank=True, related_name='good', to=settings.AUTH_USER_MODEL),
        ),
    ]
