# Generated by Django 3.2.9 on 2021-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211208_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_cnt',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
